=encoding utf8

=head1 The Binary Puzzle Solver credits and thanks file

=head2 NOTE

If you believe your name is missing here, please contact me at
L<http://www.shlomifish.org/me/contact-me/>.

=head2 List of Credits.

=over 4

=item * Shlomi Fish

Doing the bulk of the work on the solver.

=item * Meir Maor

Giving a talk about the Scala programming language on August Penguin 2012,
which prompted work on the solver.

=item * Richard Klement (tybalt89)

Writing an alternative solver in hacky perl and releasing it as open-source
software under the MIT/X11 license.

=item * Steve Klabnik

Writing a
L<http://timelessrepo.com/making-ruby-gems,tutorial for making ruby Gems> which
proved to be useful. Also answered some questions on IRC

=item * judyfor from #ruby-lang on Freenode

Answering some questions, and recommending an rspec rakefile integration
snippet.

=item * Kizano_werk from #perl on Freenode

Helping me diagnose a rubygems.org HTTP problem that prevented me from
uploading this gem (and other gems in the future).

=back 4

